import jsPDF from "jspdf";
import { formatCurrency } from "./utils";

interface ReportData {
  period: string;
  totalIncome: number;
  totalExpenses: number;
  netProfit: number;
  deductibleExpenses: number;
  taxableIncome: number;
  estimatedTax: number;
  hustleBreakdown: { name: string; income: number }[];
  expenseBreakdown: { category: string; amount: number }[];
}

export function generatePDF(data: ReportData) {
  const doc = new jsPDF();
  const gold = [201, 168, 76]; // #C9A84C

  // Header
  doc.setFontSize(22);
  doc.setTextColor(gold[0], gold[1], gold[2]);
  doc.text("Side Hustle Tracker", 20, 25);

  doc.setFontSize(12);
  doc.setTextColor(100, 100, 100);
  doc.text(`Report: ${data.period}`, 20, 35);

  // Summary
  doc.setFontSize(14);
  doc.setTextColor(0, 0, 0);
  doc.text("Summary", 20, 50);

  doc.setFontSize(11);
  const summaryY = 60;
  doc.text(`Total Income: ${formatCurrency(data.totalIncome)}`, 20, summaryY);
  doc.text(
    `Total Expenses: ${formatCurrency(data.totalExpenses)}`,
    20,
    summaryY + 8
  );
  doc.text(
    `Net Profit: ${formatCurrency(data.netProfit)}`,
    20,
    summaryY + 16
  );
  doc.text(
    `Tax-Deductible Expenses: ${formatCurrency(data.deductibleExpenses)}`,
    20,
    summaryY + 24
  );
  doc.text(
    `Taxable Income: ${formatCurrency(data.taxableIncome)}`,
    20,
    summaryY + 32
  );
  doc.text(
    `Estimated Tax: ${formatCurrency(data.estimatedTax)}`,
    20,
    summaryY + 40
  );

  // Income by hustle
  let y = summaryY + 56;
  doc.setFontSize(14);
  doc.text("Income by Hustle", 20, y);
  y += 10;
  doc.setFontSize(11);
  for (const h of data.hustleBreakdown) {
    doc.text(`${h.name}: ${formatCurrency(h.income)}`, 25, y);
    y += 8;
  }

  // Expenses by category
  y += 8;
  doc.setFontSize(14);
  doc.text("Expenses by Category", 20, y);
  y += 10;
  doc.setFontSize(11);
  for (const e of data.expenseBreakdown) {
    doc.text(`${e.category}: ${formatCurrency(e.amount)}`, 25, y);
    y += 8;
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(
    "Generated by Side Hustle Tracker - Available on TVR App Store",
    20,
    285
  );

  doc.save(`hustle-report-${data.period.toLowerCase().replace(/\s/g, "-")}.pdf`);
}
